substitutions:
  _REGION: us-east1
  _SERVICE_NAME: dynamic-ppp-api
  _AR_REPOSITORY: ppp-api
  _IMAGE_NAME: dynamic-ppp-api
  _MEMORY: 512Mi
  _CPU: "1"
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "10"

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --service-account=${_SERVICE_NAME}-runner@$PROJECT_ID.iam.gserviceaccount.com
      - --port=8000
      - --memory=${_MEMORY}
      - --cpu=${_CPU}
      - --min-instances=${_MIN_INSTANCES}
      - --max-instances=${_MAX_INSTANCES}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
